version: "3.7"

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password -h 127.0.0.1
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: db_example
    ports:
      - 3306:3306
    networks: 
      - backend
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3003:8080
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata: