version: "0.1"

services:
  pizza-backend:
    container_name: pizza-backend
    build: .
    ports:
      - 3001:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080