version: "3.7"

services:
  sonarqube:
    image: sonarqube:lts
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    restart: always
    ports:
      - "9000:9000"
    networks: 
      - backend

networks:
  backend:

volumes:
  sonar_data:
  sonar_extensions: