version: "3.7"

services:
  pizza-backend:
    container_name: pizza-backend
    build: .
    ports:
      - 3001:8080
    environment:
      -  MYSQL_HOST=db
    networks: 
      - backend
      - frontend

networks:
  backend:
  frontend: