version: "0.1"

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password -h 127.0.0.1
    restart: always
    environment:
      -  MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3003:8080